### ISSUE TITLE
incrementLimit

### ISSUE THREAD

**Issue by ghost** [AdamBrodzinski/react-ive-meteor#3]
Hi, what do you think about the incrementation limits and how to pass them to subscriptions?
Actually we could just use the Sessions from meteor by Incrementing it on the one side and get the Session again from the other side for the subscription. In this case we don't even need the getInitialState() method. But this seams not the favored way to be.. If we shouldn't use it, how should we do it instead?

**Comment by AdamBrodzinski** [comment]
That's a good question.

My first thought is that having the feed limit in Session could be brittle because it could not get cleared out when leaving the feed. Also other components could mess with it since it's global (important in a larger team, less so with a single person).

Since the FeedData component is only concerned with the feed, it seems like a great place to store state. The FeedData is basically a View Controller at this point.

I'm also thinking about having a subscription manager outside of the components to handle some of this. That way the component just notifies this manager that it needs incremented and the manager can handle subscriptions. In this case it makes more sense for it to use Session since it's not in React.  This could also utilize https://github.com/meteorhacks/subs-manager  to make caching easier.

Then the Feed could just call something like `SubsManager.subscribeTo('feed', ...)` and `SubsManager.increment('feed', 5)` or something like that.

thoughts?

**Comment by ghost** [comment]
Hmm, I also not really sure. I like the components approach, that every thing you need your component should provide you. And I am also a bit afraid because of the side effects from Session. The Session is a temptation to do easy data management, but it can result in a bigger chaos later when the project gets bigger. I've created an example of using the Session to see both approaches in parallel..

https://github.com/dropfen/react-ive-meteor/commit/16bd6bea3673bc43aa26c1c3d20caa55e73a7e02

**Comment by ghost** [comment]
Ok, I made some improvements on my forked version. Got rid of the Session, and made some changes in the publish method. Take a look ;)

https://github.com/dropfen/react-ive-meteor/commit/c9211af7cb3de2c83bf802d92dcf6d423e1f5e83

**Comment by AdamBrodzinski** [comment]
Interesting, i'll check it out!
