### ISSUE TITLE
Question on Component Instantiation 

### ISSUE THREAD

**Issue by nicholasalanbrown** [AdamBrodzinski/react-ive-meteor#7]
Hey!

Great start project. I'm starting a second Meteor project and looking to use React for the views, and came across your repo. It seems like a perfect starting point, I just had one question - why do you deviate from the standard component instantiation described in the Meteor React Preview docs http://react-in-meteor.readthedocs.org/en/latest/meteor-data/:

```
var TodoListLoader = React.createClass({
  mixins: [ReactMeteorData],
  getMeteorData() {
(...)
  }
});
```

Instead, you use:

```
class FeedList extends React.Component {
  // TODO break out more button into comp
  render() {
    console.log("[FeedList] Rendering");
(..)
  }
}
```

I rewrote your code the first way and it seems to work fine....

**Comment by rozzzly** [comment]
This is something I've been wondering as well. As far as I can tell, I think he's doing it to abstract away the data from the component so it'd be accessible elsewhere as well. I could see this being beneficial in a large(/complex) project, but for something like this, something that's meant to be a basic starting point, I think its unnecessary and perhaps disadvantageous. But then again, I don't know what he's thinking so I might be way off.

**Comment by AdamBrodzinski** [comment]
Ah, yea sorry about that, should I add something to the readme?

Some of the components use the ES6 classes which instantiate a bit different. This was introduced in 0.13 [more info](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#es6-classes).

One of the cons of ES6 classes is that you can't use mixins with them. That's why [FeedContainer](https://github.com/AdamBrodzinski/react-ive-meteor/blob/master/both/components/Feed/FeedContainer.jsx) has the `createClass` way and [FeedList](https://github.com/AdamBrodzinski/react-ive-meteor/blob/master/both/components/Feed/FeedList.jsx) is using ES6 classes.

You only need to use the `ReactMeteorData` mixin if you're using `getMeteorData`, which watches a reactive data source and triggers a re-render if data changes. Since FeedList is only using props, it's not needed.

In this example below, `sub.ready` is reactive and will re-render when new data is available from the subscription. 

```
  getMeteorData: function() {
    var sub = this.startMeteorSubscriptions();

    return {
      feedReady: sub.ready(),
      postItems: FeedDomain.getAllFeedPosts(),
      postIds: FeedDomain.getPostCommentIds()
    };
  },
```

You could use ES6 classes and the mixin by making a higher order component, i've been wanting to try that out to (not in master branch as it may be confusing)

Does this clear things up?
Cheers!

**Comment by AdamBrodzinski** [comment]
@nicholasalanbrown 

> Great start project. I'm starting a second Meteor project and looking to use React for the views, and came across your repo. 

You also may want to checkout my flux leaderboard example if using the flux architecture might be something for your project. It works great for larger projects that have shared state across multiple components.
